{
 "title": "POS Microservices - Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"user-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Product Query Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"product-query-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Product Command Service Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"product-command-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Order Service Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"order-service\"} |= ``"
    }
   ]
  }
 ]
}