{
 "title": "POS Microservices - RED",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(echo_request_duration_seconds_bucket{job=~\"user-service-service|product-query-service-service|product-command-service-service|order-service-service\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (rate(echo_requests_total{job=~\"user-service-service|product-query-service-service|product-command-service-service|order-service-service\", code=~\"5..\"}[5m])) / sum by (job) (rate(echo_requests_total{job=~\"user-service-service|product-query-service-service|product-command-service-service|order-service-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (\n  rate(echo_requests_total{job=~\"product-query-service-service|user-service-service|product-command-service-service|order-service-service\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}