apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        istio.io/rev: default
    spec:
      containers:
      - name: user-service
        image: alimikegami/pos:user-service-latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user-service-config
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: http-metrics