apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: default
  labels:
    app: user-service   
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http-metrics
      protocol: TCP
      port: 8081
      targetPort: 8081