apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-command-service-deployment
  labels:
    app: product-command-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-command-service
  template:
    metadata:
      labels:
        app: product-command-service
    spec:
      containers:
      - name: product-command-service
        image: alimikegami/pos:product-command-service-latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: product-command-service-config
        ports:
        - containerPort: 8080