apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: alimikegami/pos:product-service-latest
        envFrom:
        - configMapRef:
            name: product-service-config
        ports:
        - containerPort: 8080