apiVersion: v1
kind: Service
metadata:
  name: product-command-service-service
spec:
  selector:
    app: product-command-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051