apiVersion: apps/v1
kind: Deployment
metadata:
  name:  product-query-service-deployment
  labels:
    app:  product-query-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  product-query-service
  template:
    metadata:
      labels:
        app:  product-query-service
        istio.io/rev: default
    spec:
      containers:
      - name:  product-query-service
        image: alimikegami/pos:product-query-service-latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name:  product-query-service-config
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50051
          name: grpc
          protocol: TCP
        - containerPort: 8081
          name: http-metrics