// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductCommandService_UpdateProductQuantity_FullMethodName = "/product.ProductCommandService/UpdateProductQuantity"
)

// ProductCommandServiceClient is the client API for ProductCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductCommandServiceClient interface {
	UpdateProductQuantity(ctx context.Context, in *UpdateProductQuantityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type productCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCommandServiceClient(cc grpc.ClientConnInterface) ProductCommandServiceClient {
	return &productCommandServiceClient{cc}
}

func (c *productCommandServiceClient) UpdateProductQuantity(ctx context.Context, in *UpdateProductQuantityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProductCommandService_UpdateProductQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductCommandServiceServer is the server API for ProductCommandService service.
// All implementations must embed UnimplementedProductCommandServiceServer
// for forward compatibility.
type ProductCommandServiceServer interface {
	UpdateProductQuantity(context.Context, *UpdateProductQuantityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProductCommandServiceServer()
}

// UnimplementedProductCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductCommandServiceServer struct{}

func (UnimplementedProductCommandServiceServer) UpdateProductQuantity(context.Context, *UpdateProductQuantityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductQuantity not implemented")
}
func (UnimplementedProductCommandServiceServer) mustEmbedUnimplementedProductCommandServiceServer() {}
func (UnimplementedProductCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductCommandServiceServer will
// result in compilation errors.
type UnsafeProductCommandServiceServer interface {
	mustEmbedUnimplementedProductCommandServiceServer()
}

func RegisterProductCommandServiceServer(s grpc.ServiceRegistrar, srv ProductCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductCommandService_ServiceDesc, srv)
}

func _ProductCommandService_UpdateProductQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).UpdateProductQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_UpdateProductQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).UpdateProductQuantity(ctx, req.(*UpdateProductQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductCommandService_ServiceDesc is the grpc.ServiceDesc for ProductCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductCommandService",
	HandlerType: (*ProductCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProductQuantity",
			Handler:    _ProductCommandService_UpdateProductQuantity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}

const (
	ProductQueryService_GetProductPriceInfo_FullMethodName = "/product.ProductQueryService/GetProductPriceInfo"
)

// ProductQueryServiceClient is the client API for ProductQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductQueryServiceClient interface {
	GetProductPriceInfo(ctx context.Context, in *ProductPriceInfoRequest, opts ...grpc.CallOption) (*ProductPriceInfoResponse, error)
}

type productQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductQueryServiceClient(cc grpc.ClientConnInterface) ProductQueryServiceClient {
	return &productQueryServiceClient{cc}
}

func (c *productQueryServiceClient) GetProductPriceInfo(ctx context.Context, in *ProductPriceInfoRequest, opts ...grpc.CallOption) (*ProductPriceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductPriceInfoResponse)
	err := c.cc.Invoke(ctx, ProductQueryService_GetProductPriceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductQueryServiceServer is the server API for ProductQueryService service.
// All implementations must embed UnimplementedProductQueryServiceServer
// for forward compatibility.
type ProductQueryServiceServer interface {
	GetProductPriceInfo(context.Context, *ProductPriceInfoRequest) (*ProductPriceInfoResponse, error)
	mustEmbedUnimplementedProductQueryServiceServer()
}

// UnimplementedProductQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductQueryServiceServer struct{}

func (UnimplementedProductQueryServiceServer) GetProductPriceInfo(context.Context, *ProductPriceInfoRequest) (*ProductPriceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductPriceInfo not implemented")
}
func (UnimplementedProductQueryServiceServer) mustEmbedUnimplementedProductQueryServiceServer() {}
func (UnimplementedProductQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductQueryServiceServer will
// result in compilation errors.
type UnsafeProductQueryServiceServer interface {
	mustEmbedUnimplementedProductQueryServiceServer()
}

func RegisterProductQueryServiceServer(s grpc.ServiceRegistrar, srv ProductQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductQueryService_ServiceDesc, srv)
}

func _ProductQueryService_GetProductPriceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductPriceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).GetProductPriceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductQueryService_GetProductPriceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).GetProductPriceInfo(ctx, req.(*ProductPriceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductQueryService_ServiceDesc is the grpc.ServiceDesc for ProductQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductQueryService",
	HandlerType: (*ProductQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductPriceInfo",
			Handler:    _ProductQueryService_GetProductPriceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
