// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: product_command.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Product) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProductQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantityRequest) Reset() {
	*x = UpdateProductQuantityRequest{}
	mi := &file_product_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantityRequest) ProtoMessage() {}

func (x *UpdateProductQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantityRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductQuantityRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductPriceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceInfoRequest) Reset() {
	*x = ProductPriceInfoRequest{}
	mi := &file_product_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceInfoRequest) ProtoMessage() {}

func (x *ProductPriceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceInfoRequest.ProtoReflect.Descriptor instead.
func (*ProductPriceInfoRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{2}
}

func (x *ProductPriceInfoRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ProductPriceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceInfoResponse) Reset() {
	*x = ProductPriceInfoResponse{}
	mi := &file_product_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceInfoResponse) ProtoMessage() {}

func (x *ProductPriceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceInfoResponse.ProtoReflect.Descriptor instead.
func (*ProductPriceInfoResponse) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{3}
}

func (x *ProductPriceInfoResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_product_command_proto protoreflect.FileDescriptor

const file_product_command_proto_rawDesc = "" +
	"\n" +
	"\x15product_command.proto\x12\x0fproduct_command\x1a\x1bgoogle/protobuf/empty.proto\"\x90\x01\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"T\n" +
	"\x1cUpdateProductQuantityRequest\x124\n" +
	"\bproducts\x18\x01 \x03(\v2\x18.product_command.ProductR\bproducts\":\n" +
	"\x17ProductPriceInfoRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"P\n" +
	"\x18ProductPriceInfoResponse\x124\n" +
	"\bproducts\x18\x01 \x03(\v2\x18.product_command.ProductR\bproducts2w\n" +
	"\x15ProductCommandService\x12^\n" +
	"\x15UpdateProductQuantity\x12-.product_command.UpdateProductQuantityRequest\x1a\x16.google.protobuf.Empty2\x81\x01\n" +
	"\x13ProductQueryService\x12j\n" +
	"\x13GetProductPriceInfo\x12(.product_command.ProductPriceInfoRequest\x1a).product_command.ProductPriceInfoResponseBEZCgithub.com/alimikegami/pos-microservices/product-command-service/pbb\x06proto3"

var (
	file_product_command_proto_rawDescOnce sync.Once
	file_product_command_proto_rawDescData []byte
)

func file_product_command_proto_rawDescGZIP() []byte {
	file_product_command_proto_rawDescOnce.Do(func() {
		file_product_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)))
	})
	return file_product_command_proto_rawDescData
}

var file_product_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_product_command_proto_goTypes = []any{
	(*Product)(nil),                      // 0: product_command.Product
	(*UpdateProductQuantityRequest)(nil), // 1: product_command.UpdateProductQuantityRequest
	(*ProductPriceInfoRequest)(nil),      // 2: product_command.ProductPriceInfoRequest
	(*ProductPriceInfoResponse)(nil),     // 3: product_command.ProductPriceInfoResponse
	(*emptypb.Empty)(nil),                // 4: google.protobuf.Empty
}
var file_product_command_proto_depIdxs = []int32{
	0, // 0: product_command.UpdateProductQuantityRequest.products:type_name -> product_command.Product
	0, // 1: product_command.ProductPriceInfoResponse.products:type_name -> product_command.Product
	1, // 2: product_command.ProductCommandService.UpdateProductQuantity:input_type -> product_command.UpdateProductQuantityRequest
	2, // 3: product_command.ProductQueryService.GetProductPriceInfo:input_type -> product_command.ProductPriceInfoRequest
	4, // 4: product_command.ProductCommandService.UpdateProductQuantity:output_type -> google.protobuf.Empty
	3, // 5: product_command.ProductQueryService.GetProductPriceInfo:output_type -> product_command.ProductPriceInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_command_proto_init() }
func file_product_command_proto_init() {
	if File_product_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_product_command_proto_goTypes,
		DependencyIndexes: file_product_command_proto_depIdxs,
		MessageInfos:      file_product_command_proto_msgTypes,
	}.Build()
	File_product_command_proto = out.File
	file_product_command_proto_goTypes = nil
	file_product_command_proto_depIdxs = nil
}
