apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  labels:
    app: order-service
  namespace: default
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http-metrics
      protocol: TCP
      port: 8081
      targetPort: 8081